import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Radio, Calendar, Share2, Check, ArrowLeft } from 'lucide-react';

export default function ReportHeader({ userQuery, timestamp }) {
  const [copied, setCopied] = useState(false);

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const formattedDate = timestamp
    ? new Date(timestamp).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
      }).toUpperCase()
    : new Date().toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
      }).toUpperCase();

  return (
    <div className="w-full bg-[#EAE6FE] dark:bg-[#1B1833] text-[#18181B] dark:text-[#F3F4F6] border-b-2 border-[#18181B] dark:border-[#3F3F46] border-t-4 border-t-[#6C5CE7] py-5 sm:py-7 px-3 sm:px-6 lg:px-8 font-mono shadow-brutal-sm">
      <div className="max-w-6xl mx-auto space-y-3 sm:space-y-4">
        {/* Top Controls */}
        <div className="flex items-center justify-between gap-2">
          <Link
            to="/"
            className="px-3 py-1.5 bg-white dark:bg-[#16181E] border-2 border-[#18181B] dark:border-[#3F3F46] text-[10px] sm:text-xs font-bold text-[#18181B] dark:text-[#F3F4F6] shadow-brutal-sm hover:-translate-x-0.5 hover:-translate-y-0.5 transition-all flex items-center gap-1.5 shrink-0"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>[ NEW ANALYSIS ]</span>
          </Link>

          <button
            onClick={handleShare}
            className="px-3 py-1.5 bg-[#6C5CE7] text-white border-2 border-[#18181B] dark:border-[#3F3F46] text-[10px] sm:text-xs font-bold shadow-brutal-sm hover:-translate-x-0.5 hover:-translate-y-0.5 transition-all flex items-center gap-1.5 cursor-pointer shrink-0"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-[#B8E986]" />
                <span>LINK COPIED!</span>
              </>
            ) : (
              <>
                <Share2 className="w-3.5 h-3.5" />
                <span>[ SHARE REPORT ↗ ]</span>
              </>
            )}
          </button>
        </div>

        {/* Small Technical Badge */}
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-[#101114] text-[#C9BFFF] text-[10px] sm:text-[11px] font-bold tracking-wider uppercase border border-[#18181B] dark:border-[#3F3F46] shadow-brutal-sm max-w-full truncate">
            <Radio className="w-3 h-3 text-[#6C5CE7] animate-pulse" />
            <span>SIGNAL INTELLIGENCE REPORT</span>
          </div>
        </div>

        {/* Large User Query Title */}
        <h1 className="font-display text-xl sm:text-3xl lg:text-4xl font-extrabold text-[#18181B] dark:text-[#F3F4F6] uppercase tracking-tight leading-tight break-words">
          {userQuery}
        </h1>

        {/* Metadata Line */}
        <div className="flex flex-wrap items-center gap-x-2.5 gap-y-1 text-[10px] sm:text-xs text-[#18181B]/80 dark:text-gray-300 font-bold border-t-2 border-[#18181B]/20 dark:border-white/10 pt-3">
          <div className="flex items-center gap-1 text-[#6C5CE7]">
            <Radio className="w-3 h-3" />
            <span>GENERATED BY SIGNALAI</span>
          </div>
          <span className="text-[#18181B]/40 dark:text-gray-500">•</span>
          <div className="flex items-center gap-1">
            <Calendar className="w-3.5 h-3.5 text-[#FF7A59]" />
            <span>{formattedDate}</span>
          </div>
          <span className="text-[#18181B]/40 dark:text-gray-500">•</span>
          <span className="text-[#18181B] dark:text-white px-1.5 py-0.5 bg-white dark:bg-[#16181E] border border-[#18181B] dark:border-[#3F3F46] text-[9px] sm:text-[10px]">
            MULTI-SOURCE ANALYSIS
          </span>
        </div>
      </div>
    </div>
  );
}
